language: python
python:
  - "3.5"

script:
  - "mkdir tmp"
  - "python tests.py"

notifications:
  slack:
    secure: RIM+1XR3pbwa9dvgbZAdVTpPKxR+225XBz2Fi5Q3ghURqHfdtVGW9cHz7NqpPzZSpViep2lFcd4rcwUH0Ar4sAZIZY8aPXMv2dCGbNqb2aBwfxMjHRkhbvjPFZ7TX2OOYWTHnmXk9RZugbtdhCwNpOfdVcZ/YHKWAonXOTmw2MOop+S7m2a8ugpvT9sWM/XnRiqVNTtzX6MJO5RT9GAlVAAoLqafp+MhqqcKY79WfKmwTO0LpjQGmNMizCAiBMf42sK8lllug7sL1Q8prQJ0MYHLP+Fz0KnKuV0e+bXFHnF310txFKqUPwfDm8UHGxs+zBj6ASjCGbGOlnqJzwB5YFGxmaNHBunk2xNm3qJVeAQJS75cK4zDJa3vrYf1bTnVaI4nzUS7/5xzgU3ZCgT9oNBwe281n9u/eXzo95gOjWui1LcwDrufOX0ZPMG1j526pHT8hGbir6O90x7TRcH/spuHUkCslzr4G/27JbgBgNKg0X2xZhXqGlsKl8VeRFGJrP9Q6KT0ygfTvOPVNin2N3kbqfS6Hdd3mIKt1K83dS+TWl85eRfV4ZR8SqZbGnzaiAjex/Vnk7CzSj+7CIGTQP0tfyu3xGLrLoMmrGAxUTJ7dxPYshG7X8qTjP8QDO8Kne8BfnH533yFNVptnA7UGlGHUVHYqQXTdTG0RXvcLws=
